import { Component, OnInit } from '@angular/core';

import { EstimateService } from '../services/estimate.service';

@Component({
    selector: 'app-predict',
    templateUrl: './predict.component.html',
    styleUrls: ['./predict.component.scss']
})
export class PredictComponent implements OnInit {
    procedureName: string;
    hospitalRegion: string;
    estTotalPayment: string = '0';

    constructor(private estimateService: EstimateService) { }

    ngOnInit() {
    }

    requestEstimate() {
        this.estimateService.calculateEstimate(this.procedureName, this.hospitalRegion)
            .subscribe(data => {
                this.estTotalPayment = data.Results.output1.value.Values[0][3];
            })
    }

    procedures = [
        '039 - EXTRACRANIAL PROCEDURES W/O CC/MCC',
        '057 - DEGENERATIVE NERVOUS SYSTEM DISORDERS W/O MCC',
        '064 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W MCC',
        '065 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W CC',
        '066 - INTRACRANIAL HEMORRHAGE OR CEREBRAL INFARCTION W/O CC/MCC',
        '069 - TRANSIENT ISCHEMIA',
        '074 - CRANIAL & PERIPHERAL NERVE DISORDERS W/O MCC',
        '101 - SEIZURES W/O MCC',
        '149 - DYSEQUILIBRIUM',
        '176 - PULMONARY EMBOLISM W/O MCC',
        '177 - RESPIRATORY INFECTIONS & INFLAMMATIONS W MCC',
        '178 - RESPIRATORY INFECTIONS & INFLAMMATIONS W CC',
        '189 - PULMONARY EDEMA & RESPIRATORY FAILURE',
        '190 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W MCC',
        '191 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W CC',
        '192 - CHRONIC OBSTRUCTIVE PULMONARY DISEASE W/O CC/MCC',
        '193 - SIMPLE PNEUMONIA & PLEURISY W MCC',
        '194 - SIMPLE PNEUMONIA & PLEURISY W CC',
        '195 - SIMPLE PNEUMONIA & PLEURISY W/O CC/MCC',
        '202 - BRONCHITIS & ASTHMA W CC/MCC',
        '203 - BRONCHITIS & ASTHMA W/O CC/MCC',
        '207 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT 96+ HOURS',
        '208 - RESPIRATORY SYSTEM DIAGNOSIS W VENTILATOR SUPPORT <96 HOURS',
        '238 - MAJOR CARDIOVASC PROCEDURES W/O MCC',
        '243 - PERMANENT CARDIAC PACEMAKER IMPLANT W CC',
        '244 - PERMANENT CARDIAC PACEMAKER IMPLANT W/O CC/MCC',
        '246 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W MCC OR 4+ VESSELS/STENTS',
        '247 - PERC CARDIOVASC PROC W DRUG-ELUTING STENT W/O MCC',
        '249 - PERC CARDIOVASC PROC W NON-DRUG-ELUTING STENT W/O MCC',
        '251 - PERC CARDIOVASC PROC W/O CORONARY ARTERY STENT W/O MCC',
        '252 - OTHER VASCULAR PROCEDURES W MCC',
        '253 - OTHER VASCULAR PROCEDURES W CC',
        '254 - OTHER VASCULAR PROCEDURES W/O CC/MCC',
        '291 - HEART FAILURE & SHOCK W MCC',
        '292 - HEART FAILURE & SHOCK W CC',
        '293 - HEART FAILURE & SHOCK W/O CC/MCC',
        '300 - PERIPHERAL VASCULAR DISORDERS W CC',
        '301 - PERIPHERAL VASCULAR DISORDERS W/O CC/MCC',
        '303 - ATHEROSCLEROSIS W/O MCC',
        '305 - HYPERTENSION W/O MCC',
        '308 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W MCC',
        '309 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W CC',
        '310 - CARDIAC ARRHYTHMIA & CONDUCTION DISORDERS W/O CC/MCC',
        '312 - SYNCOPE & COLLAPSE',
        '313 - CHEST PAIN',
        '314 - OTHER CIRCULATORY SYSTEM DIAGNOSES W MCC',
        '315 - OTHER CIRCULATORY SYSTEM DIAGNOSES W CC',
        '329 - MAJOR SMALL & LARGE BOWEL PROCEDURES W MCC',
        '330 - MAJOR SMALL & LARGE BOWEL PROCEDURES W CC',
        '372 - MAJOR GASTROINTESTINAL DISORDERS & PERITONEAL INFECTIONS W CC',
        '377 - G.I. HEMORRHAGE W MCC',
        '378 - G.I. HEMORRHAGE W CC',
        '379 - G.I. HEMORRHAGE W/O CC/MCC',
        '389 - G.I. OBSTRUCTION W CC',
        '390 - G.I. OBSTRUCTION W/O CC/MCC',
        '394 - OTHER DIGESTIVE SYSTEM DIAGNOSES W CC',
        '418 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W CC',
        '419 - LAPAROSCOPIC CHOLECYSTECTOMY W/O C.D.E. W/O CC/MCC',
        '439 - DISORDERS OF PANCREAS EXCEPT MALIGNANCY W CC',
        '460 - SPINAL FUSION EXCEPT CERVICAL W/O MCC',
        '469 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W MCC',
        '470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC',
        '473 - CERVICAL SPINAL FUSION W/O CC/MCC',
        '480 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W MCC',
        '481 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W CC',
        '482 - HIP & FEMUR PROCEDURES EXCEPT MAJOR JOINT W/O CC/MCC',
        '491 - BACK & NECK PROC EXC SPINAL FUSION W/O CC/MCC',
        '536 - FRACTURES OF HIP & PELVIS W/O MCC',
        '552 - MEDICAL BACK PROBLEMS W/O MCC',
        '602 - CELLULITIS W MCC',
        '603 - CELLULITIS W/O MCC',
        '638 - DIABETES W CC',
        '682 - RENAL FAILURE W MCC',
        '683 - RENAL FAILURE W CC',
        '684 - RENAL FAILURE W/O CC/MCC',
        '689 - KIDNEY & URINARY TRACT INFECTIONS W MCC',
        '690 - KIDNEY & URINARY TRACT INFECTIONS W/O MCC',
        '698 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W MCC',
        '699 - OTHER KIDNEY & URINARY TRACT DIAGNOSES W CC',
        '811 - RED BLOOD CELL DISORDERS W MCC',
        '812 - RED BLOOD CELL DISORDERS W/O MCC',
        '853 - INFECTIOUS & PARASITIC DISEASES W O.R. PROCEDURE W MCC',
        '870 - SEPTICEMIA OR SEVERE SEPSIS W MV 96+ HOURS',
        '871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W MCC',
        '872 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W/O MCC',
        '885 - PSYCHOSES',
        '897 - ALCOHOL/DRUG ABUSE OR DEPENDENCE W/O REHABILITATION THERAPY W/O MCC',
        '917 - POISONING & TOXIC EFFECTS OF DRUGS W MCC',
        '918 - POISONING & TOXIC EFFECTS OF DRUGS W/O MCC',
        '948 - SIGNS & SYMPTOMS W/O MCC'
    ];

    regions = [
        'AK - Anchorage',
        'AL - Birmingham',
        'AL - Dothan',
        'AL - Huntsville',
        'AL - Mobile',
        'AL - Montgomery',
        'AL - Tuscaloosa',
        'AR - Fort Smith',
        'AR - Jonesboro',
        'AR - Little Rock',
        'AR - Springdale',
        'AR - Texarkana',
        'AZ - Mesa',
        'AZ - Phoenix',
        'AZ - Sun City',
        'AZ - Tucson',
        'CA - Alameda County',
        'CA - Bakersfield',
        'CA - Chico',
        'CA - Contra Costa County',
        'CA - Fresno',
        'CA - Los Angeles',
        'CA - Modesto',
        'CA - Napa',
        'CA - Orange County',
        'CA - Palm Springs/Rancho M',
        'CA - Redding',
        'CA - Sacramento',
        'CA - Salinas',
        'CA - San Bernardino',
        'CA - San Diego',
        'CA - San Francisco',
        'CA - San Jose',
        'CA - San Luis Obispo',
        'CA - San Mateo County',
        'CA - Santa Barbara',
        'CA - Santa Cruz',
        'CA - Santa Rosa',
        'CA - Stockton',
        'CA - Ventura',
        'CO - Boulder',
        'CO - Colorado Springs',
        'CO - Denver',
        'CO - Fort Collins',
        'CO - Grand Junction',
        'CO - Greeley',
        'CO - Pueblo',
        'CT - Bridgeport',
        'CT - Hartford',
        'CT - New Haven',
        'DC - Washington',
        'DE - Wilmington',
        'FL - Bradenton',
        'FL - Clearwater',
        'FL - Fort Lauderdale',
        'FL - Fort Myers',
        'FL - Gainesville',
        'FL - Hudson',
        'FL - Jacksonville',
        'FL - Lakeland',
        'FL - Miami',
        'FL - Ocala',
        'FL - Orlando',
        'FL - Ormond Beach',
        'FL - Panama City',
        'FL - Pensacola',
        'FL - Sarasota',
        'FL - St. Petersburg',
        'FL - Tallahassee',
        'FL - Tampa',
        'GA - Albany',
        'GA - Atlanta',
        'GA - Augusta',
        'GA - Columbus',
        'GA - Macon',
        'GA - Rome',
        'GA - Savannah',
        'HI - Honolulu',
        'IA - Cedar Rapids',
        'IA - Davenport',
        'IA - Des Moines',
        'IA - Dubuque',
        'IA - Iowa City',
        'IA - Mason City',
        'IA - Sioux City',
        'IA - Waterloo',
        'ID - Boise',
        'ID - Idaho Falls',
        'IL - Aurora',
        'IL - Bloomington',
        'IL - Blue Island',
        'IL - Chicago',
        'IL - Elgin',
        'IL - Evanston',
        'IL - Hinsdale',
        'IL - Joliet',
        'IL - Melrose Park',
        'IL - Peoria',
        'IL - Rockford',
        'IL - Springfield',
        'IL - Urbana',
        'IN - Evansville',
        'IN - Fort Wayne',
        'IN - Gary',
        'IN - Indianapolis',
        'IN - Lafayette',
        'IN - Muncie',
        'IN - Munster',
        'IN - South Bend',
        'IN - Terre Haute',
        'KS - Topeka',
        'KS - Wichita',
        'KY - Covington',
        'KY - Lexington',
        'KY - Louisville',
        'KY - Owensboro',
        'KY - Paducah',
        'LA - Alexandria',
        'LA - Baton Rouge',
        'LA - Houma',
        'LA - Lafayette',
        'LA - Lake Charles',
        'LA - Metairie',
        'LA - Monroe',
        'LA - New Orleans',
        'LA - Shreveport',
        'LA - Slidell',
        'MA - Boston',
        'MA - Springfield',
        'MA - Worcester',
        'MD - Baltimore',
        'MD - Salisbury',
        'MD - Takoma Park',
        'ME - Bangor',
        'ME - Portland',
        'MI - Ann Arbor',
        'MI - Dearborn',
        'MI - Detroit',
        'MI - Flint',
        'MI - Grand Rapids',
        'MI - Kalamazoo',
        'MI - Lansing',
        'MI - Marquette',
        'MI - Muskegon',
        'MI - Petoskey',
        'MI - Pontiac',
        'MI - Royal Oak',
        'MI - Saginaw',
        'MI - St. Joseph',
        'MI - Traverse City',
        'MN - Duluth',
        'MN - Minneapolis',
        'MN - Rochester',
        'MN - St. Cloud',
        'MN - St. Paul',
        'MO - Cape Girardeau',
        'MO - Columbia',
        'MO - Joplin',
        'MO - Kansas City',
        'MO - Springfield',
        'MO - St. Louis',
        'MS - Gulfport',
        'MS - Hattiesburg',
        'MS - Jackson',
        'MS - Meridian',
        'MS - Oxford',
        'MS - Tupelo',
        'MT - Billings',
        'MT - Great Falls',
        'MT - Missoula',
        'NC - Asheville',
        'NC - Charlotte',
        'NC - Durham',
        'NC - Greensboro',
        'NC - Greenville',
        'NC - Hickory',
        'NC - Raleigh',
        'NC - Wilmington',
        'NC - Winston-Salem',
        'ND - Bismarck',
        'ND - Fargo/Moorhead MN',
        'ND - Grand Forks',
        'ND - Minot',
        'NE - Lincoln',
        'NE - Omaha',
        'NH - Lebanon',
        'NH - Manchester',
        'NJ - Camden',
        'NJ - Hackensack',
        'NJ - Morristown',
        'NJ - New Brunswick',
        'NJ - Newark',
        'NJ - Paterson',
        'NJ - Ridgewood',
        'NM - Albuquerque',
        'NV - Las Vegas',
        'NV - Reno',
        'NY - Albany',
        'NY - Binghamton',
        'NY - Bronx',
        'NY - Buffalo',
        'NY - East Long Island',
        'NY - Elmira',
        'NY - Manhattan',
        'NY - Rochester',
        'NY - Syracuse',
        'NY - White Plains',
        'OH - Akron',
        'OH - Canton',
        'OH - Cincinnati',
        'OH - Cleveland',
        'OH - Columbus',
        'OH - Dayton',
        'OH - Elyria',
        'OH - Kettering',
        'OH - Toledo',
        'OH - Youngstown',
        'OK - Lawton',
        'OK - Oklahoma City',
        'OK - Tulsa',
        'OR - Bend',
        'OR - Eugene',
        'OR - Medford',
        'OR - Portland',
        'OR - Salem',
        'PA - Allentown',
        'PA - Altoona',
        'PA - Danville',
        'PA - Erie',
        'PA - Harrisburg',
        'PA - Johnstown',
        'PA - Lancaster',
        'PA - Philadelphia',
        'PA - Pittsburgh',
        'PA - Reading',
        'PA - Sayre',
        'PA - Scranton',
        'PA - Wilkes-Barre',
        'PA - York',
        'RI - Providence',
        'SC - Charleston',
        'SC - Columbia',
        'SC - Florence',
        'SC - Greenville',
        'SC - Spartanburg',
        'SD - Rapid City',
        'SD - Sioux Falls',
        'TN - Chattanooga',
        'TN - Jackson',
        'TN - Johnson City',
        'TN - Kingsport',
        'TN - Knoxville',
        'TN - Memphis',
        'TN - Nashville',
        'TX - Abilene',
        'TX - Amarillo',
        'TX - Austin',
        'TX - Beaumont',
        'TX - Bryan',
        'TX - Corpus Christi',
        'TX - Dallas',
        'TX - El Paso',
        'TX - Fort Worth',
        'TX - Harlingen',
        'TX - Houston',
        'TX - Longview',
        'TX - Lubbock',
        'TX - McAllen',
        'TX - Odessa',
        'TX - San Angelo',
        'TX - San Antonio',
        'TX - Temple',
        'TX - Tyler',
        'TX - Victoria',
        'TX - Waco',
        'TX - Wichita Falls',
        'UT - Ogden',
        'UT - Provo',
        'UT - Salt Lake City',
        'VA - Arlington',
        'VA - Charlottesville',
        'VA - Lynchburg',
        'VA - Newport News',
        'VA - Norfolk',
        'VA - Richmond',
        'VA - Roanoke',
        'VA - Winchester',
        'VT - Burlington',
        'WA - Everett',
        'WA - Olympia',
        'WA - Seattle',
        'WA - Spokane',
        'WA - Tacoma',
        'WA - Yakima',
        'WI - Appleton',
        'WI - Green Bay',
        'WI - La Crosse',
        'WI - Madison',
        'WI - Marshfield',
        'WI - Milwaukee',
        'WI - Neenah',
        'WI - Wausau',
        'WV - Charleston',
        'WV - Huntington',
        'WV - Morgantown',
        'WY - Casper'
    ];
}
