import { Component, OnInit } from '@angular/core';

import { EstimateService } from '../services/estimate.service';

@Component({
    selector: 'app-predict',
    templateUrl: './predict.component.html',
    styleUrls: ['./predict.component.scss']
})
export class PredictComponent implements OnInit {
    province: string;
    variety: string;
    price: number;
    estWineRating: string = '0';

    constructor(private estimateService: EstimateService) { }

    ngOnInit() {
    }

    requestEstimate() {
        this.estimateService.calculateEstimate(this.province, this.variety, this.price)
            .subscribe(data => {
                this.estWineRating = data.Results.output1.value.Values[0][4];
            })
    }

    provinces = [
        'Aconcagua Valley',
        'Aegean',
        'Alentejano',
        'Alentejo',
        'Algarve',
        'Alsace',
        'America',
        'Andalucia',
        'Apalta',
        'Arizona',
        'Atalanti Valley',
        'Attica',
        'Australia Other',
        'Austria',
        'Awatere Valley',
        'Baden',
        'Bairrada',
        'Beaujolais',
        'Beira Interior',
        'Beiras',
        'Bekaa Valley',
        'Bio Bio Valley',
        'Bordeaux',
        'Brda',
        'Breedekloof',
        'British Columbia',
        'Bucelas',
        'Bulgaria',
        'Burgenland',
        'Burgundy',
        'Cachapoal Valley',
        'Cahul',
        'California',
        'Canelones',
        'Canterbury',
        'Carnuntum',
        'Casablanca Valley',
        'Catalonia',
        'Cederberg',
        'Central Italy',
        'Central Otago',
        'Central Spain',
        'Central Valley',
        'Cephalonia',
        'Champagne',
        'Chile',
        'Coastal Region',
        'Colchagua Valley',
        'Colorado',
        'Commandaria',
        'Constantia',
        'Corinth',
        'Crete',
        'Curico Valley',
        'Dao',
        'Dealu Mare',
        'Donauland',
        'Douro',
        'Drama',
        'Durbanville',
        'Duriense',
        'East Coast',
        'Eger',
        'Elgin',
        'Elqui Valley',
        'Epanomi',
        'Estremadura',
        'France Other',
        'Franken',
        'Franschhoek',
        'Galicia',
        'Galil',
        'Galilee',
        'Georgia',
        'Germany',
        'Gisborne',
        'Goriska Brda',
        'Greece',
        'Groenekloof',
        'Halkidiki',
        'Hawkes Bay',
        'Hemel en Aarde',
        'Hungary',
        'Idaho',
        'Israel',
        'Istria',
        'Italy Other',
        'Jonkershoek Valley',
        'Juanico',
        'Judean Hills',
        'Kakheti',
        'Kamptal',
        'Kathikas',
        'Kremstal',
        'Kumeu',
        'Languedoc-Roussillon',
        'Levante',
        'Leyda Valley',
        'Limari Valley',
        'Lisboa',
        'Loire Valley',
        'Lolol Valley',
        'Lombardy',
        'Loncomilla Valley',
        'Lontue Valley',
        'Macedonia',
        'Madeira',
        'Maipo Valley',
        'Mantinia',
        'Marchigue',
        'Marlborough',
        'Martinborough',
        'Massachusetts',
        'Maule Valley',
        'Mavrodaphne of Patras',
        'Mendoza Province',
        'Michigan',
        'Minho',
        'Missouri',
        'Mittelburgenland',
        'Moldova',
        'Molina',
        'Mosel',
        'Mosel-Saar-Ruwer',
        'Moutere',
        'Murfatlar',
        'Nahe',
        'Naoussa',
        'Negev Hills',
        'Nelson',
        'Nemea',
        'Neszmely',
        'Neusiedlersee',
        'Neusiedlersee-Hugelland',
        'New Jersey',
        'New Mexico',
        'New South Wales',
        'New York',
        'New Zealand',
        'Niederosterreich',
        'North Carolina',
        'North Dalmatia',
        'Northeastern Italy',
        'Northern Spain',
        'Northwestern Italy',
        'Ohio',
        'Ontario',
        'Oregon',
        'Osterreichischer Sekt',
        'Other',
        'Paarl',
        'Palmela',
        'Pangeon',
        'Patras',
        'Peljesac',
        'Peloponnese',
        'Peninsula de Setubal',
        'Pennsylvania',
        'Peumo',
        'Pfalz',
        'Piedmont',
        'Pirque',
        'Port',
        'Portuguese Table Wine',
        'Provence',
        'Puente Alto',
        'Rapel Valley',
        'Requinoa',
        'Rheingau',
        'Rheinhessen',
        'Rhone Valley',
        'Ribatejano',
        'Ribatejo',
        'Robertson',
        'Romania',
        'Samos',
        'Samson',
        'San Antonio',
        'San Jose',
        'Santorini',
        'Setubal',
        'Shomron',
        'Sicily & Sardinia',
        'Simonsberg-Stellenbosch',
        'Sopron',
        'South Africa',
        'South Australia',
        'South Island',
        'Southern Italy',
        'Southwest France',
        'Spain Other',
        'Spanish Islands',
        'Stajerska',
        'Stellenbosch',
        'Styria',
        'Sudoststeiermark',
        'Sudsteiermark',
        'Swartland',
        'Tasmania',
        'Tejo',
        'Terras do Sado',
        'Texas',
        'Thermenregion',
        'Thrace',
        'Thracian Valley',
        'Tikves',
        'Tokaj',
        'Tokaji',
        'Traisental',
        'Turkey',
        'Tuscany',
        'Upper Galilee',
        'Uruguay',
        'Vale dos Vinhedos',
        'Valle de Guadalupe',
        'Vanju Mare',
        'Veneto',
        'Victoria',
        'Vienna',
        'Viile Timisului',
        'Villany',
        'Vinho Espumante de Qualidade',
        'Vinho Verde',
        'Vipavska Dolina',
        'Virginia',
        'Wachau',
        'Wagram',
        'Wagram-Donauland',
        'Waiheke Island',
        'Waipara',
        'Waipara Valley',
        'Wairarapa',
        'Wairau Valley',
        'Walker Bay',
        'Washington',
        'Weinland Osterreich',
        'Weinviertel',
        'Wellington',
        'Western Australia',
        'Western Cape',
        'Wurttemberg',
        'Zupa'
    ];

    varieties = [
        'Agiorgitiko',
        'Aglianico',
        'Albana',
        'Albarino',
        'Aleatico',
        'Alfrocheiro',
        'Alicante',
        'Alicante Bouschet',
        'Aligote',
        'Alsace white blend',
        'Alvarinho',
        'Antao Vaz',
        'Aragones',
        'Arinto',
        'Arneis',
        'Assyrtico',
        'Austrian Red Blend',
        'Austrian white blend',
        'Auxerrois',
        'Baga',
        'Barbera',
        'Bical',
        'Black Muscat',
        'Blaufrankisch',
        'Bobal',
        'Bonarda',
        'Bordeaux-style Red Blend',
        'Bordeaux-style White Blend',
        'Brachetto',
        'Cabernet',
        'Cabernet Blend',
        'Cabernet Franc',
        'Cabernet Franc-Merlot',
        'Cabernet Merlot',
        'Cabernet Sauvignon',
        'Cabernet Sauvignon-Cabernet Franc',
        'Cabernet Sauvignon-Carmenere',
        'Cabernet Sauvignon-Malbec',
        'Cabernet Sauvignon-Merlot',
        'Cabernet Sauvignon-Sangiovese',
        'Cabernet Sauvignon-Shiraz',
        'Cabernet Sauvignon-Syrah',
        'Cabernet-Syrah',
        'Cannonau',
        'Carignan',
        'Carignane',
        'Carignano',
        'Carmenere',
        'Carmenere-Cabernet Sauvignon',
        'Carmenere-Syrah',
        'Carricante',
        'Castelao',
        'Catarratto',
        'Cesanese dAffile',
        'Chambourcin',
        'Champagne Blend',
        'Charbono',
        'Chardonnay',
        'Chardonnay-Sauvignon',
        'Chardonnay-Semillon',
        'Chardonnay-Viognier',
        'Chenin Blanc',
        'Chenin Blanc-Chardonnay',
        'Cinsault',
        'Claret',
        'Coda di Volpe',
        'Colombard',
        'Colombard-Sauvignon Blanc',
        'Cortese',
        'Corvina',
        'Counoise',
        'Dolcetto',
        'Encruzado',
        'Falanghina',
        'Fernao Pires',
        'Feteasca Neagra',
        'Fiano',
        'Frappato',
        'Friulano',
        'Fume Blanc',
        'Furmint',
        'G-S-M',
        'Gaglioppo',
        'Gamay',
        'Gamay Noir',
        'Garganega',
        'Garnacha',
        'Garnacha Blanca',
        'Garnacha-Syrah',
        'Gelber Muskateller',
        'Gewurztraminer',
        'Gewurztraminer-Riesling',
        'Glera',
        'Godello',
        'Graciano',
        'Grauburgunder',
        'Grecanico',
        'Greco',
        'Grenache',
        'Grenache Blanc',
        'Grenache-Shiraz',
        'Grenache-Syrah',
        'Grillo',
        'Gros and Petit Manseng',
        'Gros Manseng',
        'Gruner Veltliner',
        'Hondarrabi Zuri',
        'Insolia',
        'Inzolia',
        'Johannisberg Riesling',
        'Kekfrankos',
        'Kerner',
        'Lagrein',
        'Lambrusco',
        'Lemberger',
        'Loureiro',
        'Macabeo',
        'Madeira Blend',
        'Malbec',
        'Malbec-Cabernet Sauvignon',
        'Malbec-Merlot',
        'Malbec-Syrah',
        'Malvasia',
        'Malvasia Bianca',
        'Malvasia Istriana',
        'Marsanne',
        'Marsanne-Roussanne',
        'Mavrodaphne',
        'Melon',
        'Mencia',
        'Meritage',
        'Merlot',
        'Merlot-Cabernet',
        'Merlot-Cabernet Franc',
        'Merlot-Cabernet Sauvignon',
        'Merlot-Malbec',
        'Monastrell',
        'Monastrell-Syrah',
        'Monica',
        'Montepulciano',
        'Moscadello',
        'Moscatel',
        'Moscato',
        'Moscato Giallo',
        'Moschofilero',
        'Mourvedre',
        'Muller-Thurgau',
        'Muscadel',
        'Muscat',
        'Muscat Blanc',
        'Muscat Canelli',
        'Muskat Ottonel',
        'Nebbiolo',
        'Negrette',
        'Negroamaro',
        'Nerello Mascalese',
        'Nero dAvola',
        'Nero di Troia',
        'Norton',
        'Nuragus',
        'Orange Muscat',
        'Pallagrello',
        'Palomino',
        'Passerina',
        'Pecorino',
        'Pedro Ximenez',
        'Perricone',
        'Petit Manseng',
        'Petit Verdot',
        'Petite Sirah',
        'Petite Verdot',
        'Picolit',
        'Piedirosso',
        'Pinot Auxerrois',
        'Pinot Bianco',
        'Pinot Blanc',
        'Pinot Grigio',
        'Pinot Gris',
        'Pinot Meunier',
        'Pinot Nero',
        'Pinot Noir',
        'Pinotage',
        'Plavac Mali',
        'Port',
        'Portuguese Red',
        'Portuguese Sparkling',
        'Portuguese White',
        'Prieto Picudo',
        'Primitivo',
        'Prosecco',
        'Provence red blend',
        'Prugnolo Gentile',
        'Raboso',
        'Red Blend',
        'Refosco',
        'Rhone-style Red Blend',
        'Rhone-style White Blend',
        'Ribolla Gialla',
        'Riesling',
        'Rkatsiteli',
        'Roditis',
        'Rosado',
        'Rosato',
        'Rose',
        'Roter Veltliner',
        'Rotgipfler',
        'Roussanne',
        'Roussanne-Viognier',
        'Ruche',
        'Sagrantino',
        'Sangiovese',
        'Sangiovese Grosso',
        'Saperavi',
        'Sauvignon',
        'Sauvignon Blanc',
        'Sauvignon Blanc-Chardonnay',
        'Sauvignon Blanc-Semillon',
        'Sauvignon Gris',
        'Scheurebe',
        'Semillon',
        'Semillon-Chardonnay',
        'Semillon-Sauvignon Blanc',
        'Sherry',
        'Shiraz',
        'Shiraz-Cabernet Sauvignon',
        'Shiraz-Grenache',
        'Shiraz-Viognier',
        'Silvaner',
        'Sparkling Blend',
        'Spatburgunder',
        'St. Laurent',
        'Sylvaner',
        'Syrah',
        'Syrah-Cabernet',
        'Syrah-Cabernet Sauvignon',
        'Syrah-Grenache',
        'Syrah-Petite Sirah',
        'Syrah-Viognier',
        'Tannat',
        'Tannat-Cabernet',
        'Tempranillo',
        'Tempranillo Blend',
        'Tempranillo-Cabernet Sauvignon',
        'Tempranillo-Garnacha',
        'Tempranillo-Merlot',
        'Tempranillo-Shiraz',
        'Teran',
        'Teroldego',
        'Tinta de Toro',
        'Tinta Fina',
        'Tinta Roriz',
        'Tinto del Pais',
        'Tinto Fino',
        'Tocai Friulano',
        'Tokaji',
        'Tokay',
        'Torrontes',
        'Touriga Franca',
        'Touriga Nacional',
        'Touriga Nacional Blend',
        'Touriga Nacional-Cabernet Sauvignon',
        'Traminer',
        'Traminette',
        'Trebbiano',
        'Trebbiano di Lugana',
        'Trincadeira',
        'Turbiana',
        'Ugni Blanc-Colombard',
        'Uva di Troia',
        'Verdejo',
        'Verdejo-Viura',
        'Verdelho',
        'Verdicchio',
        'Verduzzo Friulano',
        'Vermentino',
        'Vernaccia',
        'Vidal Blanc',
        'Vignoles',
        'Viognier',
        'Viognier-Chardonnay',
        'Viognier-Roussanne',
        'Viura',
        'Viura-Chardonnay',
        'Vranec',
        'Weissburgunder',
        'Welschriesling',
        'White Blend',
        'White Riesling',
        'Xarel-lo',
        'Xinomavro',
        'Zibibbo',
        'Zierfandler',
        'Zinfandel',
        'Zweigelt'
    ];
}
